spring.application.name=restfulApiInMap
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/InMap_DB
spring.datasource.username=postgres
spring.datasource.password=2236213111
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/plain
server.compression.min-response-size=1024

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.username=GestionAppInMap@yahoo.com
spring.mail.password=xsmtpsib-65bf2fd005b8a764a49b0b39d79d17402e6131c6781ad08db018ebefe7c395bd-TdiGm3OdTrhq5Ew2
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false


